# Generated by Django 5.1.7 on 2025-03-10 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoAtividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Tipo de Atividade",
                "verbose_name_plural": "Tipos de Atividades",
            },
        ),
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("data_hora_inicio", models.DateTimeField()),
                ("data_hora_fim", models.DateTimeField()),
                ("n_vagas", models.PositiveIntegerField(default=0)),
                ("n_inscricoes", models.PositiveIntegerField(default=0)),
                ("emite_certificado", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atividades",
                        to="eventos.evento",
                    ),
                ),
                (
                    "palestrantes",
                    models.ManyToManyField(
                        related_name="atividades", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atividades",
                        to="eventos.tipoatividade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atividade",
                "verbose_name_plural": "Atividades",
            },
        ),
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmada", models.BooleanField(default=False)),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscritos",
                        to="eventos.atividade",
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscricoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscrição",
                "verbose_name_plural": "Inscrições",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("participante", "atividade"), name="unique_inscricao"
                    )
                ],
            },
        ),
    ]
