# Generated by Django 5.1.7 on 2025-03-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0002_tipoatividade_atividade_inscricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participante",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="participante",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
