# Generated by Django 5.1.7 on 2025-03-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0003_alter_participante_email_alter_participante_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="participante",
            name="bio",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="participante",
            name="is_palestrante",
            field=models.BooleanField(default=False),
        ),
    ]
