# Generated by Django 5.1.7 on 2025-03-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0004_participante_bio_participante_is_palestrante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipoatividade",
            name="nome",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
