# Generated by Django 5.1.7 on 2025-03-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0005_alter_tipoatividade_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="participante",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="palestrantes/"),
        ),
    ]
