# Generated by Django 5.1.7 on 2025-03-13 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0006_participante_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividade",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atividades",
                to="eventos.tipoatividade",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="organizador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
