# Generated by Django 5.1.7 on 2025-03-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0007_alter_atividade_tipo_alter_evento_organizador"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="eventos/"),
        ),
    ]
