# Generated by Django 5.1.7 on 2025-03-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0008_evento_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="atividades/"),
        ),
    ]
