# Generated by Django 5.1.7 on 2025-03-14 23:50

import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0009_atividade_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividade",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to=eventos.models.atividade_imagem_upload
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to=eventos.models.evento_imagem_upload
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="foto",
            field=models.ImageField(
                blank=True, null=True, upload_to=eventos.models.participante_foto_upload
            ),
        ),
    ]
