# Generated by Django 5.1.7 on 2025-03-15 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0010_alter_atividade_imagem_alter_evento_imagem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricao",
            name="codigo_confirmacao",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
