# Generated by Django 5.1.7 on 2025-03-15 23:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0011_inscricao_codigo_confirmacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricao",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inscricao",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
