# Generated by Django 5.1.7 on 2025-03-16 00:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0012_inscricao_created_at_inscricao_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "data_emissao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="usuarios/certificados/"
                    ),
                ),
                (
                    "atividade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificados",
                        to="eventos.atividade",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificados_evento",
                        to="eventos.evento",
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "unique_together": {("participante", "atividade", "evento")},
            },
        ),
    ]
