# Generated by Django 5.1.7 on 2025-03-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0013_certificado"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricao",
            name="certificado_emitido",
            field=models.BooleanField(default=False),
        ),
    ]
