# Generated by Django 5.1.7 on 2025-03-16 16:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0014_inscricao_certificado_emitido"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="codigo_confirmacao",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
