# Generated by Django 5.2.17
# Adiciona o campo categoria ao Evento (com as choices) e atribui a
# categoria correta aos eventos já existentes.
#
# O campo entra com default "formacao"; na sequência, o data migration
# ajusta os eventos que já existiam (por chave no título).

from django.db import migrations, models


def atribuir_categorias(apps, schema_editor):
    Evento = apps.get_model("eventos", "Evento")
    mapa = {
        "semana nacional": "ciencia",
        "mcps e llms": "tecnologia",
        "curso de html": "tecnologia",
        "html": "tecnologia",
    }
    for ev in Evento.objects.all():
        chave = (ev.title or "").lower()
        for k, cat in mapa.items():
            if k in chave:
                ev.categoria = cat
                break
        ev.save()


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0015_atividade_codigo_confirmacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("formacao", "Formação"),
                    ("ciencia", "Ciência"),
                    ("tecnologia", "Tecnologia"),
                    ("cultura", "Cultura"),
                    ("outros", "Outros"),
                ],
                default="formacao",
                max_length=20,
            ),
        ),
        migrations.RunPython(atribuir_categorias, migrations.RunPython.noop),
    ]