# Generated by Django 5.2.17 on 2026-09-10 19:40

import eventos.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0016_evento_categoria'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='participante',
            managers=[
                ('objects', eventos.managers.ParticipanteManager()),
            ],
        ),
    ]
