# Generated by Django 5.2.17 on 2026-09-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0017_alter_participante_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="categoria",
            field=models.CharField(default="formacao", max_length=60),
        ),
    ]
