# Generated by Django 5.2.17 on 2026-09-11 19:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0018_alter_evento_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="Presenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("organizador", "Organizador"),
                            ("palestrante", "Palestrante"),
                            ("participante", "Participante"),
                        ],
                        default="participante",
                        max_length=20,
                    ),
                ),
                (
                    "registrada_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("qr", "QR do crachá"),
                            ("codigo", "Código digitado"),
                            ("manual", "Marcação manual"),
                        ],
                        default="qr",
                        max_length=10,
                    ),
                ),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencas",
                        to="eventos.atividade",
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presencas_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Presença",
                "verbose_name_plural": "Presenças",
                "ordering": ["-registrada_em"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("atividade", "participante"), name="unique_presenca"
                    )
                ],
            },
        ),
    ]
