# Generated by Django 5.2.17 on 2026-09-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0019_presenca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presenca",
            name="origem",
            field=models.CharField(
                choices=[
                    ("qr", "QR do crachá"),
                    ("auto", "Automática (câmera da organização)"),
                    ("proprio", "A própria pessoa confirmou"),
                    ("codigo", "Código digitado"),
                    ("manual", "Marcação manual"),
                ],
                default="qr",
                max_length=10,
            ),
        ),
    ]
