# Generated by Django 5.2.17 on 2026-09-12 19:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0021_cpf_digitos_nao_unico"),
    ]

    operations = [
        migrations.CreateModel(
            name="PresencaCancelada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atividade_titulo",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "pessoa_nome",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("papel", models.CharField(blank=True, default="", max_length=20)),
                ("origem", models.CharField(blank=True, default="", max_length=10)),
                ("registrada_em", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelada_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("motivo", models.CharField(blank=True, default="", max_length=120)),
                (
                    "atividade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presencas_canceladas",
                        to="eventos.atividade",
                    ),
                ),
                (
                    "cancelada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presencas_canceladas_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="presencas_canceladas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Presença cancelada",
                "verbose_name_plural": "Presenças canceladas",
                "ordering": ["-cancelada_em"],
            },
        ),
    ]
