# Generated by Django 5.2.17 on 2026-09-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0022_presencacancelada"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="modelo_cracha",
            field=models.CharField(
                choices=[("etiqueta", "Etiqueta"), ("classico", "Clássico")],
                default="etiqueta",
                max_length=20,
            ),
        ),
    ]
