# Generated by Django 5.2.17 on 2026-09-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0023_evento_modelo_cracha"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="local",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
