# Generated by Django 5.2.17 on 2026-09-15 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0024_atividade_local"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipanteMetadados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dados", models.JSONField(blank=True, default=dict)),
                (
                    "participante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Metadados do participante",
                "verbose_name_plural": "Metadados dos participantes",
            },
        ),
    ]
