# Generated by Django 5.2.17 on 2026-09-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0025_participantemetadados"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlunoRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("nome", models.CharField(blank=True, default="", max_length=255)),
                ("cpf", models.CharField(blank=True, default="", max_length=11)),
                ("dados", models.JSONField(blank=True, default=dict)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Aluno (planilha)",
                "verbose_name_plural": "Alunos (planilha)",
            },
        ),
    ]
