# Generated by Django 5.2.17 on 2026-09-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0026_alunoroster"),
    ]

    operations = [
        migrations.AddField(
            model_name="alunoroster",
            name="confere",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alunoroster",
            name="dados_usuario",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alunoroster",
            name="usado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
