# Generated by Django 5.2.17 on 2026-09-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0030_favorito"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="publicada",
            field=models.BooleanField(default=True),
        ),
    ]
