# Generated by Django 5.2.17 on 2026-09-17 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0031_atividade_publicada"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="decidida_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atividade",
            name="decidida_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="propostas_decididas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="atividade",
            name="motivo_rejeicao",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="atividade",
            name="proponente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="propostas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="atividade",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("organizador", "Criada pelo organizador"),
                    ("pendente", "Aguardando aprovação"),
                    ("aprovada", "Proposta aprovada"),
                    ("rejeitada", "Proposta rejeitada"),
                ],
                db_index=True,
                default="organizador",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="atividade",
            name="tipo_sugerido",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.CreateModel(
            name="ChamadaProposicoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        default="Chamada de propostas de atividades", max_length=255
                    ),
                ),
                ("descricao", models.TextField(blank=True, default="")),
                ("inicio", models.DateTimeField()),
                ("fim", models.DateTimeField()),
                ("aberta", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chamada",
                        to="eventos.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chamada de proposições",
                "verbose_name_plural": "Chamadas de proposições",
            },
        ),
        migrations.CreateModel(
            name="Espaco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=160)),
                ("capacidade", models.PositiveIntegerField(default=0)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="espacos",
                        to="eventos.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Espaço",
                "verbose_name_plural": "Espaços",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Vaga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField()),
                ("fim", models.DateTimeField()),
                ("capacidade", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "espaco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vagas",
                        to="eventos.espaco",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vagas",
                        to="eventos.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaga da chamada",
                "verbose_name_plural": "Vagas da chamada",
                "ordering": ["inicio", "espaco__nome"],
            },
        ),
        migrations.AddField(
            model_name="atividade",
            name="vaga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="propostas",
                to="eventos.vaga",
            ),
        ),
        migrations.AddConstraint(
            model_name="espaco",
            constraint=models.UniqueConstraint(
                fields=("evento", "nome"), name="unique_espaco_evento"
            ),
        ),
        migrations.AddConstraint(
            model_name="vaga",
            constraint=models.UniqueConstraint(
                fields=("espaco", "inicio", "fim"), name="unique_vaga_espaco_janela"
            ),
        ),
    ]
