# Generated by Django 5.2.17 on 2026-09-17 12:38

import unicodedata

from django.conf import settings
from django.db import migrations, models


def semear_espacos(apps, schema_editor):
    """Semeia o catálogo de espaços com o que o campus já usa nas atividades.

    Os nomes saem do campo livre `Atividade.local` (vários separados por
    vírgula), passando pelos apelidos da agenda (`AGENDA_ALIASES_LOCAL`) e
    normalizados sem acento/caixa, para "Auditório" e "Auditorio" não virarem
    duas linhas. Espaço que já existe é RENOMEADO para o nome oficial em vez de
    criar linha nova — é assim que a capacidade já informada não se perde.
    """
    Espaco = apps.get_model("eventos", "Espaco")
    Atividade = apps.get_model("eventos", "Atividade")

    aliases = getattr(settings, "AGENDA_ALIASES_LOCAL", None) or {}

    def chave(nome):
        base = unicodedata.normalize("NFD", str(nome or "").lower())
        return "".join(c for c in base if unicodedata.category(c) != "Mn").strip()

    # 1) Nomes oficiais, na ordem em que aparecem nas atividades.
    oficiais = {}
    for local in Atividade.objects.exclude(local="").values_list("local", flat=True):
        for parte in (local or "").split(","):
            nome = " ".join(parte.split())
            if not nome:
                continue
            nome = aliases.get(nome, nome)
            oficiais.setdefault(chave(nome), nome)

    # 2) Já cadastrados: renomeia para o nome oficial (sem duplicar).
    for espaco in list(Espaco.objects.all()):
        oficial = oficiais.get(chave(espaco.nome))
        if not oficial or oficial == espaco.nome:
            continue
        # Outra linha já usa o nome oficial? Então não mexe nesta.
        if Espaco.objects.filter(nome=oficial).exists():
            continue
        espaco.nome = oficial
        espaco.save(update_fields=["nome"])

    # 3) Cria o que ainda falta.
    for nome in oficiais.values():
        Espaco.objects.get_or_create(nome=nome)


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0032_atividade_decidida_em_atividade_decidida_por_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="espaco",
            name="unique_espaco_evento",
        ),
        migrations.RemoveField(
            model_name="espaco",
            name="evento",
        ),
        migrations.AlterField(
            model_name="espaco",
            name="nome",
            field=models.CharField(max_length=160, unique=True),
        ),
        migrations.RunPython(semear_espacos, migrations.RunPython.noop),
    ]
