# Generated by Django 5.2.17 on 2026-09-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0033_remove_espaco_unique_espaco_evento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContextoIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chave",
                    models.SlugField(max_length=60, unique=True, verbose_name="Chave"),
                ),
                ("rotulo", models.CharField(max_length=120, verbose_name="Rótulo")),
                (
                    "grupo",
                    models.CharField(
                        choices=[
                            ("geral", "Geral"),
                            ("participante", "Participante"),
                            ("organizador", "Organizador"),
                            ("graficos", "Gráficos"),
                        ],
                        default="geral",
                        max_length=20,
                        verbose_name="Grupo",
                    ),
                ),
                (
                    "tipo_padrao",
                    models.CharField(
                        choices=[
                            ("texto", "Redação (texto)"),
                            ("classificacao", "Classificação"),
                        ],
                        default="classificacao",
                        help_text="Qual padrão do ambiente usar quando o modelo não for informado.",
                        max_length=20,
                        verbose_name="Padrão quando vazio",
                    ),
                ),
                (
                    "modelo",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ex.: gpt-4o, gpt-4o-mini, gpt-5.6-luna. Vazio = padrão do ambiente.",
                        max_length=80,
                        verbose_name="Modelo de LLM",
                    ),
                ),
                (
                    "temperatura",
                    models.FloatField(
                        blank=True,
                        help_text="Opcional. Vazio = usa o valor do código.",
                        null=True,
                        verbose_name="Temperatura",
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Opcional. Vazio = usa o valor do código.",
                        null=True,
                        verbose_name="Máx. tokens",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Contexto de IA",
                "verbose_name_plural": "Contextos de IA",
                "ordering": ["grupo", "ordem", "rotulo"],
            },
        ),
    ]
