# Generated by Django 5.2.17 on 2026-09-20 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0035_seed_contextos_ia"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="consentimento_voluntario",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="atividade",
            name="recursos_necessarios",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="PalestranteSugerido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("telefone", models.CharField(blank=True, default="", max_length=40)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="palestrantes_sugeridos",
                        to="eventos.atividade",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="palestrantes_sugeridos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="palestrantes_sugeridos_vinculados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Palestrante sugerido",
                "verbose_name_plural": "Palestrantes sugeridos",
                "ordering": ["criado_em", "id"],
            },
        ),
    ]
