# Generated by Django 5.2.17 on 2026-09-20 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0036_atividade_consentimento_voluntario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="equipe",
            field=models.ManyToManyField(
                blank=True, related_name="eventos_equipe", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="participante",
            name="is_equipe",
            field=models.BooleanField(default=False),
        ),
    ]
