# Generated by Django 5.2.17 on 2026-09-21 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0037_evento_equipe_participante_is_equipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="organizadores",
            field=models.ManyToManyField(
                blank=True,
                related_name="eventos_coorganizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
