# Generated by Django 5.2.17 on 2026-09-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0038_evento_organizadores"),
    ]

    operations = [
        migrations.AddField(
            model_name="participante",
            name="foto_social_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
