# Generated by Django 5.2.17 on 2026-09-23 21:49

import django.db.models.deletion
import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0039_participante_foto_social_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assinante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cargo", models.CharField(blank=True, default="", max_length=150)),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=eventos.models.assinatura_imagem_upload,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Assinante de certificado",
                "verbose_name_plural": "Assinantes de certificado",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="atividade",
            name="carga_horaria",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificado",
            name="carga_horaria",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificado",
            name="tipo",
            field=models.CharField(
                choices=[("atividade", "Atividade"), ("evento", "Evento")],
                db_index=True,
                default="atividade",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="carga_horaria",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="percentual_certificado",
            field=models.PositiveSmallIntegerField(default=75),
        ),
        migrations.CreateModel(
            name="ConfiguracaoCertificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(default="CERTIFICADO", max_length=150)),
                (
                    "corpo",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Texto do certificado. Aceita variáveis entre {{ }}.",
                    ),
                ),
                ("rodape", models.CharField(blank=True, default="", max_length=255)),
                (
                    "modo_layout",
                    models.CharField(
                        choices=[
                            ("fundo", "Fundo (imagem/PDF) + texto"),
                            ("docx", "Modelo .docx"),
                        ],
                        default="fundo",
                        max_length=10,
                    ),
                ),
                (
                    "layout_fundo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=eventos.models.certificado_fundo_upload,
                    ),
                ),
                (
                    "template_docx",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=eventos.models.certificado_template_upload,
                    ),
                ),
                (
                    "carga_horaria_padrao",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("percentual", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("enviar_email", models.BooleanField(default=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "evento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificado_config",
                        to="eventos.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de certificado",
                "verbose_name_plural": "Configurações de certificado",
            },
        ),
        migrations.CreateModel(
            name="AssinaturaCertificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cargo", models.CharField(blank=True, default="", max_length=150)),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=eventos.models.assinatura_imagem_upload,
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField(default=1)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to="eventos.configuracaocertificado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura do certificado",
                "verbose_name_plural": "Assinaturas do certificado",
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.AddField(
            model_name="certificado",
            name="config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificados",
                to="eventos.configuracaocertificado",
            ),
        ),
    ]
