# Generated by Django 5.2.17 on 2026-09-23 23:52

import django.db.models.deletion
import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0040_assinante_atividade_carga_horaria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaocertificado",
            name="atividade",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificado_config",
                to="eventos.atividade",
            ),
        ),
        migrations.AddField(
            model_name="configuracaocertificado",
            name="escopo",
            field=models.CharField(
                choices=[("evento", "Evento"), ("atividade", "Atividade")],
                default="evento",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="configuracaocertificado",
            name="evento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificado_configs",
                to="eventos.evento",
            ),
        ),
        migrations.AlterField(
            model_name="configuracaocertificado",
            name="layout_fundo",
            field=models.ImageField(
                blank=True, null=True, upload_to=eventos.models.certificado_fundo_upload
            ),
        ),
        migrations.AlterField(
            model_name="configuracaocertificado",
            name="modo_layout",
            field=models.CharField(
                choices=[
                    ("texto", "Só texto (fundo padrão)"),
                    ("fundo", "Imagem de fundo + texto"),
                    ("docx", "Modelo .docx"),
                ],
                default="texto",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="configuracaocertificado",
            constraint=models.UniqueConstraint(
                condition=models.Q(("atividade__isnull", True), ("escopo", "evento")),
                fields=("evento",),
                name="uniq_cert_config_evento",
            ),
        ),
        migrations.AddConstraint(
            model_name="configuracaocertificado",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("atividade__isnull", True), ("escopo", "atividade")
                ),
                fields=("evento",),
                name="uniq_cert_config_atividades",
            ),
        ),
    ]
