# Generated by Django 5.2.17 on 2026-09-24 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0041_configuracaocertificado_atividade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assinaturacertificado",
            name="origem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="eventos.assinante",
            ),
        ),
    ]
