# Generated by Django 5.2.17 on 2026-09-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0042_assinaturacertificado_origem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuracaocertificado",
            name="modo_layout",
            field=models.CharField(
                choices=[
                    ("texto", "Texto livre (imagem de fundo opcional)"),
                    ("docx", "Modelo .docx"),
                ],
                default="texto",
                max_length=10,
            ),
        ),
    ]
