# Generated by Django 5.2.17 on 2026-09-24 14:09

import os

import django.db.models.deletion
import eventos.models
from django.conf import settings
from django.db import migrations, models


def importar_templates(apps, schema_editor):
    """Leva cada `template_docx` já configurado para o catálogo e vincula.

    Reaproveita o próprio arquivo (mesmo caminho no storage), sem reenviar.
    Modelos repetidos entre configs compartilham a mesma linha do catálogo.
    """
    Config = apps.get_model("eventos", "ConfiguracaoCertificado")
    Template = apps.get_model("eventos", "TemplateCertificadoDocx")

    cache = {}
    for config in Config.objects.all():
        caminho = getattr(config.template_docx, "name", "") if config.template_docx else ""
        if not caminho:
            continue
        template = cache.get(caminho)
        if template is None:
            escopo = "evento" if config.escopo == "evento" else "atividade"
            template = Template.objects.create(
                nome=os.path.basename(caminho),
                escopo=escopo,
                arquivo=caminho,
            )
            cache[caminho] = template
        config.template = template
        config.save(update_fields=["template"])


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0044_configuracaocertificado_fundo_para_texto"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateCertificadoDocx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "escopo",
                    models.CharField(
                        choices=[("evento", "Evento"), ("atividade", "Atividade")],
                        max_length=12,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to=eventos.models.certificado_template_upload
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo .docx de certificado",
                "verbose_name_plural": "Modelos .docx de certificado",
                "ordering": ["-criado_em", "id"],
            },
        ),
        migrations.AddField(
            model_name="configuracaocertificado",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="configuracoes",
                to="eventos.templatecertificadodocx",
            ),
        ),
        migrations.RunPython(importar_templates, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="configuracaocertificado",
            name="template_docx",
        ),
    ]
