# Generated by Django 5.2.17 on 2026-09-24 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0046_catalogo_fundos"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("request_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "usuario_nome",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "usuario_email",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("web", "Site"),
                            ("api", "API"),
                            ("admin", "Admin"),
                            ("cli", "Linha de comando"),
                            ("sistema", "Sistema"),
                        ],
                        default="web",
                        max_length=10,
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("criar", "Criar"),
                            ("editar", "Editar"),
                            ("excluir", "Excluir"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("emitir_certificado", "Emitir certificado"),
                            ("aprovar_proposta", "Aprovar proposta"),
                            ("rejeitar_proposta", "Rejeitar proposta"),
                            ("cancelar_proposta", "Cancelar proposta"),
                            ("importar", "Importar"),
                            ("configurar_certificado", "Configurar certificado"),
                            ("checkin", "Check-in"),
                            ("cancelar_presenca", "Cancelar presença"),
                            ("erro", "Erro"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "entidade",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=60
                    ),
                ),
                (
                    "objeto_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "objeto_repr",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("resumo", models.CharField(blank=True, default="", max_length=255)),
                ("detalhes", models.JSONField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("path", models.CharField(blank=True, default="", max_length=255)),
                ("metodo", models.CharField(blank=True, default="", max_length=10)),
                ("status", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditoria",
                        to="eventos.evento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de auditoria",
                "verbose_name_plural": "Registros de auditoria",
                "ordering": ["-criado_em", "-id"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "-criado_em"], name="auditoria_usuario_idx"
                    ),
                    models.Index(
                        fields=["acao", "-criado_em"], name="auditoria_acao_idx"
                    ),
                    models.Index(
                        fields=["entidade", "objeto_id"], name="auditoria_objeto_idx"
                    ),
                    models.Index(fields=["-criado_em"], name="auditoria_criado_idx"),
                ],
            },
        ),
    ]
