# Generated by Django 5.2.17 on 2026-09-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0047_registro_auditoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="exige_inscricao",
            field=models.BooleanField(default=True, verbose_name="Exige inscrição"),
        ),
    ]
