# Generated by Django 5.2.17 on 2026-09-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0048_atividade_exige_inscricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="margem_presenca_antes_min",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="margem_presenca_depois_min",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
