# Generated by Django 5.2.17 on 2026-09-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0049_evento_margem_presenca_antes_min_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="margem_presenca_antes_min",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="atividade",
            name="margem_presenca_depois_min",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
