# Generated by Django 5.2.17 on 2026-09-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0050_atividade_margem_presenca_antes_min_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participante",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
    ]
