# Generated by Django 5.2.17 on 2026-09-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0051_participante_atualizado_em"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participante",
            name="is_equipe",
            field=models.BooleanField(default=False, verbose_name="Equipe de apoio"),
        ),
        migrations.AlterField(
            model_name="participante",
            name="is_organizador",
            field=models.BooleanField(default=False, verbose_name="Organizador"),
        ),
        migrations.AlterField(
            model_name="participante",
            name="is_palestrante",
            field=models.BooleanField(default=False, verbose_name="Palestrante"),
        ),
        migrations.AlterField(
            model_name="participante",
            name="is_participante",
            field=models.BooleanField(default=True, verbose_name="Participante"),
        ),
    ]
