# Generated by Django 5.2.17 on 2026-09-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0052_alter_participante_is_equipe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="senha_padrao",
            field=models.CharField(
                default="@snct2026", max_length=128, verbose_name="Senha padrão"
            ),
        ),
    ]
