# Generated by Django 5.2.17 on 2026-10-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0053_evento_senha_padrao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presenca",
            name="papel",
            field=models.CharField(
                choices=[
                    ("organizador", "Organizador"),
                    ("palestrante", "Palestrante"),
                    ("equipe", "Equipe de apoio"),
                    ("participante", "Participante"),
                ],
                default="participante",
                max_length=20,
            ),
        ),
    ]
