# Generated by Django 5.2.17 on 2026-09-28 16:39

import blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("eventos", "0052_alter_participante_is_equipe_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "autor_nome",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("resumo", models.CharField(blank=True, default="", max_length=300)),
                ("corpo", models.TextField()),
                (
                    "capa",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=blog.models.storage_blog,
                        upload_to=blog.models.capa_upload,
                    ),
                ),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("pendente", "Aguardando aprovação"),
                            ("publicado", "Publicado"),
                            ("oculto", "Oculto"),
                        ],
                        db_index=True,
                        default="pendente",
                        max_length=12,
                    ),
                ),
                ("fixado", models.BooleanField(default=False)),
                ("publicado_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts_blog",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts_blog",
                        to="eventos.evento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post do blog",
                "verbose_name_plural": "Posts do blog",
                "ordering": ["-fixado", "-publicado_em", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="FotoPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        storage=blog.models.storage_blog,
                        upload_to=blog.models.foto_upload,
                    ),
                ),
                ("legenda", models.CharField(blank=True, default="", max_length=255)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="blog.postevento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto do post",
                "verbose_name_plural": "Fotos do post",
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="postevento",
            index=models.Index(
                fields=["evento", "situacao", "-publicado_em"],
                name="blog_evento_situacao_idx",
            ),
        ),
    ]
