"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
from dj_database_url import parse as db_url
from django.contrib.messages import constants


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())

# -- Configurações de implantação (lidas do ambiente) --
# -- adicionado por Luciano Vilas Boas --
# Domínio público usado em links absolutos (QR code de certificado, e-mails).
SITE_URL = config("SITE_URL", default="http://127.0.0.1:8501").rstrip("/")

# Origem usada pelo navegador para o Socket.IO. Vazio = mesma origem da página,
# que é o correto atrás do proxy (Traefik roteia /socket.io para a porta 8500).
SOCKET_URL = config("SOCKET_URL", default="")

# Endereço interno do servidor Socket.IO (roda no mesmo contêiner, porta 8500).
# Usado pelo lado servidor (eventos/services.py) para emitir eventos.
SOCKET_INTERNAL_URL = config("SOCKET_INTERNAL_URL", default="http://127.0.0.1:8500")

# -- Versão do produto (fonte única em setup/version.py) --
# Sobrescrevível por APP_VERSION no ambiente; exposta nos templates, no admin e
# no schema da API. A versão da API REST (`/api/v1/`) é independente e continua
# em "v1" (SPECTACULAR_SETTINGS).
from setup import version as _version  # noqa: E402  (import local, sem ciclo)

APP_VERSION = config("APP_VERSION", default="") or _version.__version__
APP_VERSION_LABEL = f"v{APP_VERSION}"

# CSRF: atrás do proxy TLS o Django precisa confiar na origem. Sem isto o login
# e todos os formulários POST falham com "CSRF verification failed".
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())

# Aplicação atrás de um proxy que faz o TLS (Traefik). O Django precisa de
# dois ajustes para "saber" que a conexão original é HTTPS:
#  1) acreditar no cabeçalho X-Forwarded-Proto que o proxy envia;
#  2) redirecionar HTTP -> HTTPS.
# Sem o primeiro, o allauth monta a URL de callback do Google como
# http://... e o Google rejeita com redirect_uri_mismatch (só conhece https).
#
# IMPORTANTE: SECURE_PROXY_SSL_HEADER só deve ficar ATIVO quando há um proxy
# de verdade na frente (produção/Traefik). Em desenvolvimento local SEM proxy,
# o navegador não envia X-Forwarded-Proto; com o header configurado e ausente,
# o Django pode montar URLs de forma inconsistente. Por isso a variável
# USE_HTTPS_PROXY controla o comportamento por ambiente (.env).
USE_X_FORWARDED_HOST = config("USE_X_FORWARDED_HOST", default=True, cast=bool)
USE_HTTPS_PROXY = config("USE_HTTPS_PROXY", default=False, cast=bool)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if USE_HTTPS_PROXY else None
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=USE_HTTPS_PROXY, cast=bool)


# Application definition
  
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # "django.contrib.sites",  

]

THIRD_PARTY_APPS = [
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "drf_spectacular",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

LOCAL_APPS = [
    "eventos",
    "participante",
    "organizador",
    "relatorios",
    "api",
    "apoio",
]
 
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise serve os arquivos estáticos com DEBUG=False (obrigatório em
    # produção: o runserver deixa de servir /static/ quando DEBUG é False).
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",      
]

ROOT_URLCONF = "setup.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [ BASE_DIR / 'templates' ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Expõe SITE_URL e SOCKET_URL nos templates (configuráveis por env)
                "eventos.context_processors.deployment",
                # `?v=` dos CSS/JS calculado a partir dos arquivos (evita o
                # navegador servir CSS antigo por um ano depois do deploy)
                "eventos.context_processors.assets",
                # Formulário do modal "Editar Perfil" em todas as telas internas
                "eventos.context_processors.perfil_form",
                # Config dos metadados do participante (para o JS dos campos
                # condicionais/dependentes)
                "eventos.context_processors.metadados_config",
                # Versão do produto no footer (fonte: setup/version.py)
                "eventos.context_processors.app_version",
            ],
        },
    },
]

WSGI_APPLICATION = "setup.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# DATABASES = {
#     "default": config(
#         "DATABASE_URL", default="sqlite:///" + str(BASE_DIR / "db.sqlite3"), cast=db_url
#     )
# }
 



# DATABASES = {
#     "default": config(
#         "DATABASE_URL",
#         default="sqlite:///" + str(BASE_DIR / "db.sqlite3"),
#         cast=db_url,
#     )
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT", default=5432, cast=int),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = config("TIME_ZONE", default="America/Sao_Paulo")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [ BASE_DIR / STATIC_URL ]  # Diretório para arquivos estáticos da aplicação
STATIC_ROOT = BASE_DIR / "staticfiles"  # Diretório onde os arquivos serão coletados

# WhiteNoise: comprime e serve os estáticos coletados em STATIC_ROOT.
# "CompressedStaticFilesStorage" (sem manifest) evita quebrar o build quando
# algum arquivo referenciado não existe — o manifest é mais rígido.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}
WHITENOISE_MAX_AGE = 31536000  # 1 ano de cache (os links levam ?v= para invalidar)


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField" 


# -- Configurações da API REST (django-rest-framework) --
# -- adicionado por Luciano Vilas Boas --
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # Permite usar a sessão do site (navegador logado) sem token,
        "rest_framework.authentication.SessionAuthentication",
        # E o token para app externo/LLM (Authorization: Token <chave>)
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


# -- Configurações do schema OpenAPI (drf-spectacular) --
# -- adicionado por Luciano Vilas Boas --
SPECTACULAR_SETTINGS = {
    "TITLE": "API Nossos Eventos (IFMG)",
    "DESCRIPTION": (
        "API REST de eventos, atividades, inscrições e certificados do campus "
        "Ponte Nova. Versão do app: " + APP_VERSION_LABEL + "."
    ),
    "VERSION": "v1",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r"/api/v1",
}


# -- Configurações de CORS para a API --
# -- adicionado por Luciano Vilas Boas --
# Lista de origens autorizadas a consumir a API. Configurada via .env
# (ALLOWED_API_HOSTS) para não abrir "*". Leitura fica liberada para todos;
# funciona em conjunto com a autenticação por token.
CORS_ALLOWED_ORIGINS = []
_temp_cors = config("ALLOWED_API_HOSTS", default="", cast=Csv())
if _temp_cors:
    CORS_ALLOWED_ORIGINS = [h.strip() for h in _temp_cors if h.strip()] 


# -- Configurações para envio de e-mail pelo Google --
# -- adicionado por Luciano Vilas Boas --
# O backend padrão é o ASSÍNCRONO: o SMTP normal segura a requisição durante o
# handshake TLS e nenhum e-mail do sistema (avisos, confirmação, reset) deve
# ditar o tempo de resposta. O envio real continua SMTP — só sai numa thread.
# Para voltar ao envio síncrono, aponte EMAIL_BACKEND para
# "django.core.mail.backends.smtp.EmailBackend" no .env.
EMAIL_BACKEND = config(
    "EMAIL_BACKEND", default="eventos.mail_backend.AsyncEmailBackend"
)
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com") 
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
# Sem timeout, um SMTP travado seguraria a thread de envio indefinidamente.
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=10, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")   # Substitua pelo seu e-mail
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")  # Substitua pela senha do seu e-mail
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")  # Substitua pelo seu e-mail


# -- Configurações da API OpenAI --
# -- adicionado por Luciano Vilas Boas --
OPENAI_API_KEY = config("OPENAI_API_KEY")

# Interruptor geral dos recursos de IA. Desligado, as funções de IA nem chamam
# a OpenAI e caem direto no fallback determinístico (o restante do sistema
# continua funcionando normalmente).
IA_ATIVA = config("IA_ATIVA", default=True, cast=bool)

# Nomes de modelo centralizados (antes espalhados pelos serviços). O de texto
# redige (descrições, mensagens); o de classificação decide (tema, tipo).
IA_MODELO_TEXTO = config("IA_MODELO_TEXTO", default="gpt-4o")
IA_MODELO_CLASSIFICACAO = config("IA_MODELO_CLASSIFICACAO", default="gpt-4o-mini")


# -- Configurações de cache --
# -- adicionado por Luciano Vilas Boas --
# -- precisa rodar o comando 'python manage.py createcachetable' para criar a tabela de cache no banco de dados
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache_table",
    }
}

# -- Configurações de mensagens --
# -- adicionado por Luciano Vilas Boas -- 
MESSAGE_TAGS = {
    constants.DEBUG: 'alert-info',
    constants.INFO: 'alert-info',
    constants.SUCCESS: 'alert-success',
    constants.WARNING: 'alert-warning',
    constants.ERROR: 'alert-danger',
}  


# -- Configurações do Django Allauth --
# # -- adicionado por Luciano Vilas Boas --
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

# -- Configurações do Django Allauth --
# -- adicionado por Luciano Vilas Boas --
LOGIN_REDIRECT_URL = "/participante/dashboard"  # provisorio => depouis vai redirecionar para a dashboard do participante  
LOGOUT_REDIRECT_URL ="/eventos" # "/accounts/login"  # new

# Provider specific settings

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE' : [
            'profile',
            'email'
        ],
        # 'APP': {    # confirado na admin do djnago 
        #     'client_id': config("GOOGLE_CLIENT_ID"),
        #     'secret': config("GOOGLE_CLIENT_SECRET"),
        # },
        'AUTH_PARAMS': {
            'access_type':'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}

# -- Credenciais do login social (lidas do ambiente) --
# -- adicionado por Luciano Vilas Boas --
# Ficam aqui para que o comando "manage.py configurar_socialapp" possa
# cadastrar o provedor no banco a partir do .env, sem depender do admin.
GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID", default="")
GOOGLE_CLIENT_SECRET = config("GOOGLE_CLIENT_SECRET", default="")

# -- Configurações do Django Allauth --
# -- adicionado por Luciano Vilas Boas --
SITE_ID = 1

# Verificação de e-mail:
#  - No cadastro LOCAL (e-mail/senha), o e-mail precisa ser confirmado
#    para a conta sair da "inativa" (o e-mail de confirmação é enviado).
#  - No login SOCIAL (Google), o e-mail JÁ vem verificado da fonte; o
#    allauth não pede confirmação no fluxo social.
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

# Login social: permite que uma conta Google AUTOCADASTRE o usuário na
# primeira vez (e-mail + profile vêm do provedor), sem tela de aprovação
# manual. Sem isto, essa decisão dependeria do adapter local.
SOCIALACCOUNT_AUTO_SIGNUP = True

# Login social confiável (Google): quando o e-mail do provedor já pertence a
# uma conta local, entra NELA em vez de recusar o vínculo e exibir a tela de
# confirmação de e-mail (comportamento padrão que "finge" ter enviado o link).
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
# Vincula o SocialAccount à conta local existente, tornando o login social
# permanente (sem isso, o vínculo é refeito a cada login).
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
# O e-mail do provedor já vem verificado pelo Google; o fluxo social não exige
# confirmação. O cadastro local continua exigindo (ACCOUNT_EMAIL_VERIFICATION).
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"

# Como qualquer conta Google é aceita, o cadastro aceita o campo de e-mail
# e não exige username (o Google não fornece).
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = { 'email' }
#ACCOUNT_USERNAME_REQUIRED = False

# Cadastro pela web usa o formulário local, que acrescenta o CPF
# (obrigatório e validado por dígito verificador). O e-mail continua sendo a
# identidade da conta; o CPF NÃO é único.
ACCOUNT_FORMS = {"signup": "eventos.forms.SignupFormComCpf"}

# ---------------------------------------------------------------------------
# Metadados do participante (configuráveis por escola; SEM coluna no banco)
# ---------------------------------------------------------------------------
# Cada escola ajusta esta lista — o sistema não fixa "turma", "ano" nem nada.
# Tipos aceitos: "texto", "numero", "escolha" (com "opcoes": [...]).
# Recursos:
#   - "depende_de" + "opcoes_por": as opções do campo dependem do valor de outro
#     (ex.: ano/período muda conforme o curso);
#   - "visivel_quando": o campo só aparece/é exigido quando outro campo tem um
#     dos valores (ex.: matrícula só para Aluno; função só para Servidor).
# Os valores ficam em `ParticipanteMetadados.dados` (JSON) e aparecem no
# cadastro/perfil, na lista de presença e nos relatórios/exportações.
METADADOS_PARTICIPANTE = [
    {"chave": "vinculo", "rotulo": "Vínculo", "tipo": "escolha", "obrigatorio": True, "ordem": 1,
     "opcoes": ["Aluno", "Servidor", "Colaborador", "Estagiário", "Comunidade externa"]},

    # -- Só para Aluno -------------------------------------------------------
    {"chave": "matricula", "rotulo": "Matrícula", "tipo": "texto", "obrigatorio": True, "ordem": 2,
     "visivel_quando": {"chave": "vinculo", "valores": ["Aluno"]}},
    {"chave": "curso", "rotulo": "Curso", "tipo": "escolha", "obrigatorio": True, "ordem": 3,
     "opcoes": ["Informática", "Administração", "TPG"],
     "visivel_quando": {"chave": "vinculo", "valores": ["Aluno"]}},
    {"chave": "turma", "rotulo": "Turma", "tipo": "escolha", "ordem": 4,
     "opcoes": ["Turma 1", "Turma 2"],
     "visivel_quando": {"chave": "vinculo", "valores": ["Aluno"]}},
    {"chave": "ano", "rotulo": "Ano/Período", "tipo": "escolha", "ordem": 5,
     "depende_de": "curso",
     "opcoes_por": {
         "Informática": ["Primeiro ano", "Segundo ano", "Terceiro ano"],
         "Administração": ["Primeiro ano", "Segundo ano", "Terceiro ano"],
         "TPG": ["Primeiro período", "Segundo período", "Terceiro período",
                 "Quarto período", "Quinto período"],
     },
     "visivel_quando": {"chave": "vinculo", "valores": ["Aluno"]}},

    # -- Só para Servidor ----------------------------------------------------
    {"chave": "funcao", "rotulo": "Função", "tipo": "escolha", "obrigatorio": True, "ordem": 6,
     "opcoes": ["Professor", "Técnico administrativo"],
     "visivel_quando": {"chave": "vinculo", "valores": ["Servidor"]}},
]

# ---------------------------------------------------------------------------
# Programação (agenda): apelidos de local
# ---------------------------------------------------------------------------
# O campo `local` da atividade é texto livre e a escola escreve variações do
# mesmo espaço. Este mapa unifica os nomes no FILTRO e no agrupamento (o texto
# exibido na atividade continua o original). Ex.: "Lab. de Informática 1" e
# "Lab. de Informática" passam a ser um só lugar.
AGENDA_ALIASES_LOCAL = {
    "Sala de aula vazia (sem carteiras)": "Sala de aula",
    "Laboratório de Informática 1": "Laboratório de Informática",
}

# ---------------------------------------------------------------------------
# Chamada de proposições de atividades
# ---------------------------------------------------------------------------
# Quantas propostas ATIVAS (aguardando aprovação ou já aprovadas) cada pessoa
# pode manter por evento. 0 = sem limite. É um limite lógico, para conter abuso
# — não há constraint no banco, então dois envios simultâneos podem passar de 1.
MAX_PROPOSTAS_POR_PROPONENTE = config("MAX_PROPOSTAS_POR_PROPONENTE", default=0, cast=int)

# Avisos por e-mail da chamada (nova proposta para o organizador; decisão para
# o proponente). DESLIGADO por padrão: só ligue depois de validar o SMTP de
# produção (EMAIL_HOST_*), senão os envios falham em silêncio e param no log.
PROPOSTAS_NOTIFICAR_EMAIL = config("PROPOSTAS_NOTIFICAR_EMAIL", default=False, cast=bool)

# Ao confirmar o e-mail (botão na página do link), o usuário já sai logado.
# Sem isto ele confirma e volta para a tela de login, o que na prática faz
# muita gente achar que a confirmação não funcionou.
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# Sem prefixo no assunto. O padrão do Django é "[Django] ", que aparecia para
# o usuário final como: "[Django] Confirme seu e-mail — Nossos Eventos IFMG".
EMAIL_SUBJECT_PREFIX = ""

AUTH_USER_MODEL = 'eventos.Participante'  # new

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' 



# -- Configurações do Django Allauth --
# -- adicionado por Luciano Vilas Boas --
# ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "/accounts/email-confirmation/"
# ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "/accounts/email-confirmation/"
# ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
# ACCOUNT_ADAPTER = "eventos.adapters.CustomAccountAdapter"



# ---------------------------------------------------------------------------
# Confirmação de presença (crachá e QR da atividade)
# ---------------------------------------------------------------------------

# Janela em que a presença pode ser confirmada: abre antes da atividade começar
# e fecha depois de acabar. É o que impede o QR da atividade (que é público) de
# valer para sempre — foto compartilhada fora da janela não confirma nada.
# Ajustável por ambiente, sem tocar no código.
PRESENCA_MARGEM_ANTES_MINUTOS = config("PRESENCA_MARGEM_ANTES_MINUTOS", default=30, cast=int)
PRESENCA_MARGEM_DEPOIS_HORAS = config("PRESENCA_MARGEM_DEPOIS_HORAS", default=2, cast=int)

# Validade do código que vai dentro do QR da atividade, em segundos. A tela do
# organizador regenera o código nesse intervalo, então uma foto que circulou
# deixa de funcionar. Curto demais atrapalha quem escaneia e ainda precisa
# entrar na conta antes de confirmar.
PRESENCA_QR_VALIDADE_SEGUNDOS = config("PRESENCA_QR_VALIDADE_SEGUNDOS", default=300, cast=int)
PRESENCA_QR_INTERVALO_RENOVACAO = config("PRESENCA_QR_INTERVALO_RENOVACAO", default=120, cast=int)


# =====================================================================
# LOGS
# ---------------------------------------------------------------------
# Motivo (12/09/2026): os erros 500 do cadastro não apareciam em lugar
# nenhum. O container tinha stderr mas nada era descarregado (buffer de
# bloco), então o traceback do Django ficava preso no buffer e o
# `docker logs` só mostrava o access log do gunicorn. Sem traceback,
# diagnosticar 500 virava adivinhação.
#
# Duas medidas:
#   1) PYTHONUNBUFFERED=1 no ambiente (ver .env / .env.example) — faz o
#      Python não bufferizar stdout/stderr;
#   2) este bloco de LOGGING, que garante um handler de console com
#      destino explícito em stderr e nível definido por logger.
#
# Ajuste o nível sem mexer no código: LOG_LEVEL=DEBUG no .env.
# =====================================================================
LOG_LEVEL = config("LOG_LEVEL", default="INFO")

LOGGING = {
    "version": 1,
    # Mantém os loggers que já existem (gunicorn/uvicorn/socket.io) vivos.
    "disable_existing_loggers": False,
    "formatters": {
        "simples": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "datefmt": "%d/%b/%Y %H:%M:%S",
            "style": "{",
        },
        "detalhado": {
            "format": "[{asctime}] {levelname} {name} ({process:d}) {message}",
            "datefmt": "%d/%b/%Y %H:%M:%S",
            "style": "{",
        },
    },
    "handlers": {
        # stderr explícito: é para onde o gunicorn manda o "--error-logfile -"
        # e o que o `docker logs` captura.
        "console": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stderr",
            "formatter": "simples",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        # Requisições com erro. WARNING = 4xx (ex.: 404, 400) e ERROR = 5xx:
        # é aqui que aparece o traceback completo dos 500 — exatamente o que
        # faltava para achar o bug do CPF. Para silenciar os 404, troque para
        # "ERROR".
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "django.security": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        # Erros de SQL que o Django não deixa virar 500 (ex.: IntegrityError
        # tratado por um middleware).
        "django.db.backends": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        # Loggers da aplicação.
        "eventos": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "api": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "organizador": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}
