"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
from dj_database_url import parse as db_url
from django.contrib.messages import constants


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())

# -- Configurações de implantação (lidas do ambiente) --
# -- adicionado por Luciano Vilas Boas --
# Domínio público usado em links absolutos (QR code de certificado, e-mails).
SITE_URL = config("SITE_URL", default="http://127.0.0.1:8501").rstrip("/")

# Origem usada pelo navegador para o Socket.IO. Vazio = mesma origem da página,
# que é o correto atrás do proxy (Traefik roteia /socket.io para a porta 8500).
SOCKET_URL = config("SOCKET_URL", default="")

# Endereço interno do servidor Socket.IO (roda no mesmo contêiner, porta 8500).
# Usado pelo lado servidor (eventos/services.py) para emitir eventos.
SOCKET_INTERNAL_URL = config("SOCKET_INTERNAL_URL", default="http://127.0.0.1:8500")

# CSRF: atrás do proxy TLS o Django precisa confiar na origem. Sem isto o login
# e todos os formulários POST falham com "CSRF verification failed".
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())

# Aplicação atrás de um proxy que faz o TLS (Traefik). O Django precisa de
# dois ajustes para "saber" que a conexão original é HTTPS:
#  1) acreditar no cabeçalho X-Forwarded-Proto que o proxy envia;
#  2) redirecionar HTTP -> HTTPS.
# Sem o primeiro, o allauth monta a URL de callback do Google como
# http://... e o Google rejeita com redirect_uri_mismatch (só conhece https).
#
# IMPORTANTE: SECURE_PROXY_SSL_HEADER só deve ficar ATIVO quando há um proxy
# de verdade na frente (produção/Traefik). Em desenvolvimento local SEM proxy,
# o navegador não envia X-Forwarded-Proto; com o header configurado e ausente,
# o Django pode montar URLs de forma inconsistente. Por isso a variável
# USE_HTTPS_PROXY controla o comportamento por ambiente (.env).
USE_X_FORWARDED_HOST = config("USE_X_FORWARDED_HOST", default=True, cast=bool)
USE_HTTPS_PROXY = config("USE_HTTPS_PROXY", default=False, cast=bool)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if USE_HTTPS_PROXY else None
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=USE_HTTPS_PROXY, cast=bool)


# Application definition
  
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # "django.contrib.sites",  

]

THIRD_PARTY_APPS = [
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "drf_spectacular",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

LOCAL_APPS = [
    "eventos",
    "participante",
    "organizador",
    "relatorios",
    "api",
]
 
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise serve os arquivos estáticos com DEBUG=False (obrigatório em
    # produção: o runserver deixa de servir /static/ quando DEBUG é False).
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",      
]

ROOT_URLCONF = "setup.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [ BASE_DIR / 'templates' ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Expõe SITE_URL e SOCKET_URL nos templates (configuráveis por env)
                "eventos.context_processors.deployment",
            ],
        },
    },
]

WSGI_APPLICATION = "setup.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# DATABASES = {
#     "default": config(
#         "DATABASE_URL", default="sqlite:///" + str(BASE_DIR / "db.sqlite3"), cast=db_url
#     )
# }
 



# DATABASES = {
#     "default": config(
#         "DATABASE_URL",
#         default="sqlite:///" + str(BASE_DIR / "db.sqlite3"),
#         cast=db_url,
#     )
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT", default=5432, cast=int),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = config("TIME_ZONE", default="America/Sao_Paulo")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [ BASE_DIR / STATIC_URL ]  # Diretório para arquivos estáticos da aplicação
STATIC_ROOT = BASE_DIR / "staticfiles"  # Diretório onde os arquivos serão coletados

# WhiteNoise: comprime e serve os estáticos coletados em STATIC_ROOT.
# "CompressedStaticFilesStorage" (sem manifest) evita quebrar o build quando
# algum arquivo referenciado não existe — o manifest é mais rígido.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}
WHITENOISE_MAX_AGE = 31536000  # 1 ano de cache (os links levam ?v= para invalidar)


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField" 


# -- Configurações da API REST (django-rest-framework) --
# -- adicionado por Luciano Vilas Boas --
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # Permite usar a sessão do site (navegador logado) sem token,
        "rest_framework.authentication.SessionAuthentication",
        # E o token para app externo/LLM (Authorization: Token <chave>)
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_FILTER_BACKENDS": [
        "rest_framework.filters.SearchFilter",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


# -- Configurações do schema OpenAPI (drf-spectacular) --
# -- adicionado por Luciano Vilas Boas --
SPECTACULAR_SETTINGS = {
    "TITLE": "API Nossos Eventos (IFMG)",
    "DESCRIPTION": "API REST de eventos, atividades, inscrições e certificados do campus Ponte Nova.",
    "VERSION": "v1",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r"/api/v1",
}


# -- Configurações de CORS para a API --
# -- adicionado por Luciano Vilas Boas --
# Lista de origens autorizadas a consumir a API. Configurada via .env
# (ALLOWED_API_HOSTS) para não abrir "*". Leitura fica liberada para todos;
# funciona em conjunto com a autenticação por token.
CORS_ALLOWED_ORIGINS = []
_temp_cors = config("ALLOWED_API_HOSTS", default="", cast=Csv())
if _temp_cors:
    CORS_ALLOWED_ORIGINS = [h.strip() for h in _temp_cors if h.strip()] 


# -- Configurações para envio de e-mail pelo Google --
# -- adicionado por Luciano Vilas Boas --
EMAIL_BACKEND = config("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com") 
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")   # Substitua pelo seu e-mail
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")  # Substitua pela senha do seu e-mail
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")  # Substitua pelo seu e-mail


# -- Configurações da API OpenAI --
# -- adicionado por Luciano Vilas Boas --
OPENAI_API_KEY = config("OPENAI_API_KEY") 


# -- Configurações de cache --
# -- adicionado por Luciano Vilas Boas --
# -- precisa rodar o comando 'python manage.py createcachetable' para criar a tabela de cache no banco de dados
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache_table",
    }
}

# -- Configurações de mensagens --
# -- adicionado por Luciano Vilas Boas -- 
MESSAGE_TAGS = {
    constants.DEBUG: 'alert-info',
    constants.INFO: 'alert-info',
    constants.SUCCESS: 'alert-success',
    constants.WARNING: 'alert-warning',
    constants.ERROR: 'alert-danger',
}  


# -- Configurações do Django Allauth --
# # -- adicionado por Luciano Vilas Boas --
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

# -- Configurações do Django Allauth --
# -- adicionado por Luciano Vilas Boas --
LOGIN_REDIRECT_URL = "/participante/dashboard"  # provisorio => depouis vai redirecionar para a dashboard do participante  
LOGOUT_REDIRECT_URL ="/eventos" # "/accounts/login"  # new

# Provider specific settings

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE' : [
            'profile',
            'email'
        ],
        # 'APP': {    # confirado na admin do djnago 
        #     'client_id': config("GOOGLE_CLIENT_ID"),
        #     'secret': config("GOOGLE_CLIENT_SECRET"),
        # },
        'AUTH_PARAMS': {
            'access_type':'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}

# -- Credenciais do login social (lidas do ambiente) --
# -- adicionado por Luciano Vilas Boas --
# Ficam aqui para que o comando "manage.py configurar_socialapp" possa
# cadastrar o provedor no banco a partir do .env, sem depender do admin.
GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID", default="")
GOOGLE_CLIENT_SECRET = config("GOOGLE_CLIENT_SECRET", default="")

# -- Configurações do Django Allauth --
# -- adicionado por Luciano Vilas Boas --
SITE_ID = 1

# Verificação de e-mail:
#  - No cadastro LOCAL (e-mail/senha), o e-mail precisa ser confirmado
#    para a conta sair da "inativa" (o e-mail de confirmação é enviado).
#  - No login SOCIAL (Google), o e-mail JÁ vem verificado da fonte; o
#    allauth não pede confirmação no fluxo social.
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

# Login social: permite que uma conta Google AUTOCADASTRE o usuário na
# primeira vez (e-mail + profile vêm do provedor), sem tela de aprovação
# manual. Sem isto, essa decisão dependeria do adapter local.
SOCIALACCOUNT_AUTO_SIGNUP = True

# Como qualquer conta Google é aceita, o cadastro aceita o campo de e-mail
# e não exige username (o Google não fornece).
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_LOGIN_METHODS = { 'email' }
#ACCOUNT_USERNAME_REQUIRED = False

AUTH_USER_MODEL = 'eventos.Participante'  # new

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' 



# -- Configurações do Django Allauth --
# -- adicionado por Luciano Vilas Boas --
# ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "/accounts/email-confirmation/"
# ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "/accounts/email-confirmation/"
# ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
# ACCOUNT_ADAPTER = "eventos.adapters.CustomAccountAdapter"



# ---------------------------------------------------------------------------
# Confirmação de presença (crachá e QR da atividade)
# ---------------------------------------------------------------------------

# Janela em que a presença pode ser confirmada: abre antes da atividade começar
# e fecha depois de acabar. É o que impede o QR da atividade (que é público) de
# valer para sempre — foto compartilhada fora da janela não confirma nada.
# Ajustável por ambiente, sem tocar no código.
PRESENCA_MARGEM_ANTES_MINUTOS = config("PRESENCA_MARGEM_ANTES_MINUTOS", default=30, cast=int)
PRESENCA_MARGEM_DEPOIS_HORAS = config("PRESENCA_MARGEM_DEPOIS_HORAS", default=2, cast=int)

# Validade do código que vai dentro do QR da atividade, em segundos. A tela do
# organizador regenera o código nesse intervalo, então uma foto que circulou
# deixa de funcionar. Curto demais atrapalha quem escaneia e ainda precisa
# entrar na conta antes de confirmar.
PRESENCA_QR_VALIDADE_SEGUNDOS = config("PRESENCA_QR_VALIDADE_SEGUNDOS", default=300, cast=int)
PRESENCA_QR_INTERVALO_RENOVACAO = config("PRESENCA_QR_INTERVALO_RENOVACAO", default=120, cast=int)
